config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("findacoach.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("coach/", include("findacoach.coach.urls", namespace="coach")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

findacoach/coach/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import ClientArchiveView
from .views import ClientCreateView
from .views import ClientDetailView
from .views import ClientListView
from .views import ClientUpdateView
from .views import CoachingSessionCreateView
from .views import CoachingSessionUpdateView
from .views import index

app_name = "coach"
urlpatterns = [
    path("", index, name="dashboard"),
    path("client/list", ClientListView.as_view(), name="client_list"),
    path("client/detail/<int:pk>", ClientDetailView.as_view(), name="client_detail"),
    path("client/create/", ClientCreateView.as_view(), name="client_create"),
    path("client/<int:pk>/update", ClientUpdateView.as_view(), name="client_update"),
    path("client/<int:pk>/archive", ClientArchiveView.as_view(), name="client_archive"),
    path(
        "coachingsession/<int:client_id>/create",
        CoachingSessionCreateView.as_view(),
        name="coachingsession_create",
    ),
    path(
        "coachingsession/<int:pk>/update",
        CoachingSessionUpdateView.as_view(),
        name="coachingsession_update",
    ),
    path(
        "favicon.svg",
        RedirectView.as_view(url="/static/images/favicons/favicon.ico"),
    ),
]

findacoach/coach/models.py
# Create your models here.
"""DB models"""

from django.conf import settings
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Count
from django.db.models import Sum
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField


class TimeStampedModel(models.Model):
    """Timestamp abstract base class model"""

    created = models.DateTimeField(auto_now_add=True, verbose_name="Datum vytvoření")
    modified = models.DateTimeField(auto_now=True, verbose_name="Datum aktualizace")

    class Meta:
        """Meta class"""

        abstract = True


class Profile(TimeStampedModel):
    """Coach model, coach is a user as well"""

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="coach_user",
        verbose_name="User",
    )
    is_coach = models.BooleanField(default=True)
    # odmentorovanych hodnín - property

    class Meta:
        """Meta class"""

        verbose_name_plural = "profiles"
        # ordering = ["name"]  # noqa: ERA001

    def __str__(self):
        return f"{self.user.email}, {self.is_coach}"

    @classmethod
    def total_coached_hours(cls, coach):
        return Client.objects.filter(coach_id=coach).aggregate(
            total_hours=Sum("hours_delivered"),
        )["total_hours"]


class Client(TimeStampedModel):
    """Client model"""

    coach = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Coach",
    )
    name = models.CharField("Full Name", max_length=254, blank=False)
    email = models.EmailField(
        "Email address",
        unique=True,
        blank=False,
        null=False,
        max_length=254,
    )
    phone = PhoneNumberField("Phone number", unique=True, blank=True)
    company = models.CharField("Company", max_length=100, blank=True)
    position = models.CharField("Position", max_length=100, blank=True)
    hours_ordered = models.DecimalField(
        "Hours ordered",
        max_digits=5,
        decimal_places=1,
        blank=True,
        null=True,
        validators=[MinValueValidator(0), MaxValueValidator(999.5)],
        help_text="Hours in 0.5 steps",
    )
    hours_delivered = models.DecimalField(
        "Hours delivered",
        max_digits=5,
        decimal_places=1,
        blank=True,
        null=True,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(999.5)],
        help_text="Hours in 0.5 steps",
    )
    coaching_goal = models.TextField(
        "Coaching goal",
        blank=True,
        help_text="Client goal as per ICF definition",
    )
    archived = models.BooleanField(default=False, blank=False)

    class Meta:
        """Meta class"""

        verbose_name_plural = "clients"
        ordering = ["name"]

    def __str__(self):
        return self.name

    @classmethod
    def clients_count(cls, coach, archived):
        return Client.objects.filter(coach_id=coach, archived=archived).aggregate(
            clients=Count("name"),
        )["clients"]


def current_time():
    return timezone.now().time()


class CoachingSession(TimeStampedModel):
    """Coaching session model"""

    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name="Client")
    date = models.DateField("Date", default=timezone.now)
    time = models.TimeField("Time", default=current_time)
    duration = models.DecimalField(
        "Duration",
        max_digits=3,
        decimal_places=1,
        validators=[MinValueValidator(0.5), MaxValueValidator(12)],
        help_text="Duration in hours",
    )
    note = models.TextField("Note", blank=True)
    homework = models.TextField("Homework", blank=True)
    realized = models.BooleanField("Realized", default=False)

    class Meta:
        """Meta class"""

        verbose_name_plural = "coaching sessions"
        # ordering = ["name"]  # noqa: ERA001
        # indexes = [models.Index(fields=["email"])]  # noqa: ERA001

    def __str__(self):
        return f"{self.date}, {self.time}, {self.duration}, {self.realized}"

    @classmethod
    def upcomming_sessions(cls, coach, session_count):
        """Returns upcomming session_count sessions per coach for all clients"""
        coaching_sessions = CoachingSession.objects.filter(
            client__coach=coach,
            realized=False,
            client__archived=False,
        ).order_by("date", "time")[:session_count]
        upcomming_sessions = []
        for coaching_session in coaching_sessions:
            item = {
                "client_id": coaching_session.client.id,
                "name": coaching_session.client.name,
                "email": coaching_session.client.email,
                "phone": coaching_session.client.phone,
                "coaching_goal": coaching_session.client.coaching_goal,
                "hours_delivered": coaching_session.client.hours_delivered,
                "hours_ordered": coaching_session.client.hours_ordered,
                "session_id": coaching_session.id,
                "date": coaching_session.date,
                "time": coaching_session.time,
                "duration": coaching_session.duration,
                "homework": coaching_session.homework,
                "note": coaching_session.note,
            }
            upcomming_sessions.append(item)

        return upcomming_sessions

findacoach/coach/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column
from crispy_forms.layout import Layout
from crispy_forms.layout import Row
from django import forms

from .models import Client
from .models import CoachingSession


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = [
            "name",
            "email",
            "phone",
            "company",
            "position",
            "hours_ordered",
            "hours_delivered",
            "coaching_goal",
            "archived",
        ]
        widgets = {
            "email": forms.EmailInput(),
            "phone": forms.TextInput(attrs={"type": "tel"}),
            "hours_ordered": forms.NumberInput(
                attrs={"step": 0.5, "min": 0, "max": 40},
            ),
            "hours_delivered": forms.NumberInput(
                attrs={"step": 0.5, "min": 0, "max": 40},
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column("name", css_class="col-md-2"),
                Column("email", css_class="col-md-2"),
                Column("phone", css_class="col-md-2"),
                Column("company", css_class="col-md-3"),
                Column("position", css_class="col-md-3"),
            ),
            Row(
                Column("coaching_goal", css_class="col-md-12"),
            ),
            Row(
                Column("hours_ordered", css_class="col-md-2"),
                Column("hours_delivered", css_class="col-md-2"),
                Column("archived", css_class="col-md-2"),
            ),
        )


class CoachingSessionForm(forms.ModelForm):
    class Meta:
        model = CoachingSession
        fields = ["date", "time", "duration", "note", "homework", "realized"]
        widgets = {
            "date": forms.DateInput(attrs={"type": "date"}),
            "time": forms.TimeInput(attrs={"type": "time"}),
            "duration": forms.NumberInput(
                attrs={"step": 0.5, "min": 0, "max": 12, "value": 1},
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column("date", css_class="col-md-2"),
                Column("time", css_class="col-md-2"),
                Column("duration", css_class="col-md-2"),
                Column("realized", css_class="col-md-2"),
            ),
            Row(
                Column("note", css_class="col-md-6"),
                Column("homework", css_class="col-md-6"),
            ),
        )

findacoach/coach/views.py
from typing import Any

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView

from .forms import ClientForm
from .forms import CoachingSessionForm
from .models import Client
from .models import CoachingSession
from .models import Profile


@login_required
def index(request):
    user = request.user
    upcomming_sessions = CoachingSession.upcomming_sessions(user, 7)
    total_coached_hours = Profile.total_coached_hours(user)
    active_clients_count = Client.clients_count(user, archived=False)
    archived_clients_count = Client.clients_count(user, archived=True)

    context = {
        "coach": user.name,
        "total_coached_hours": total_coached_hours,
        "upcomming_sessions": upcomming_sessions,
        "active_clients_count": active_clients_count,
        "archived_clients_count": archived_clients_count,
    }
    return render(request, "dashboard.html", context)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = "client/list.html"

    def get_queryset(self) -> QuerySet[Any]:
        return Client.objects.filter(archived=False, coach=self.request.user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = "client/detail.html"


class ClientCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = "client/client_form.html"
    success_message = "Client sucessfully saved"
    success_url = reverse_lazy("coach:dashboard")

    def form_valid(self, form):
        form.instance.coach = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = "client/client_form.html"
    success_message = "Client sucessfully updated"
    success_url = reverse_lazy("coach:dashboard")

    def form_valid(self, form):
        form.instance.coach = self.request.user
        return super().form_valid(form)


class ClientArchiveView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Client
    fields = []  # No fields in the form
    success_message = "Client sucessfully archived"
    success_url = reverse_lazy("coach:client_list")

    def get(self, request, *args, **kwargs):
        # Skip the confirmation page and directly update the object
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.archived = True
        self.object.save()
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())


class CoachingSessionCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = CoachingSession
    form_class = CoachingSessionForm
    template_name = "coachingsession/session_form.html"
    success_message = "Coaching session sucessfully saved"
    success_url = reverse_lazy("coach:dashboard")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if "client_id" in self.kwargs:
            kwargs["initial"] = {"client": self.kwargs["client_id"]}
        return kwargs

    def form_valid(self, form):
        if "client_id" in self.kwargs:
            client_id = self.kwargs["client_id"]
            try:
                client = Client.objects.get(id=client_id)
                form.instance.client = client
            except Client.DoesNotExist:
                messages.error("Client found")
        else:
            messages.error("Client ID missing")
        return super().form_valid(form)


class CoachingSessionUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = CoachingSession
    form_class = CoachingSessionForm
    template_name = "coachingsession/session_form.html"
    success_message = "Session sucessfully updated"
    success_url = reverse_lazy("coach:dashboard")

findacoach/coach/templates/partials/button_archive_client.html
<div class="d-flex justify-content-between align-items-center mb-3">
  <a href="{% url 'coach:client_archive' pk=client.id %}"
     class="btn btn-outline-danger d-flex align-items-center justify-content-center mx-2"
     title="Archive client">
    <svg xmlns="http://www.w3.org/2000/svg"
         width="16"
         height="16"
         fill="currentColor"
         class="bi bi-archive"
         viewBox="0 0 16 16">
      <path d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5zm13-3H1v2h14zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5" />
    </svg>
    &nbsp; Archive Client
  </a>
</div>

findacoach/coach/templates/partials/button_edit_client.html
<div class="d-flex justify-content-between align-items-center mb-3">
  <a href="{% url 'coach:client_update' pk=client_id %}"
     class="btn btn-outline-primary d-flex align-items-center justify-content-center">
    <svg xmlns="http://www.w3.org/2000/svg"
         width="16"
         height="16"
         fill="currentColor"
         class="bi bi-pencil"
         viewBox="0 0 16 16">
      <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325" />
    </svg>
    &nbsp; {{ button_text }}
  </a>
</div>

findacoach/coach/templates/partials/button_edit_last_session.html
<div class="d-flex justify-content-between align-items-center mb-3">
  <a href="{% url 'coach:coachingsession_update' pk=session_id %}"
     class="btn btn-outline-primary d-flex align-items-center justify-content-center">
    <svg xmlns="http://www.w3.org/2000/svg"
         width="16"
         height="16"
         fill="currentColor"
         class="bi bi-pencil"
         viewBox="0 0 16 16">
      <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325" />
    </svg>
    &nbsp; {{ button_text }}
  </a>
</div>

findacoach/coach/templates/partials/button_new_client.html
<a href="{% url 'coach:client_create' %}"
   class="btn btn-outline-success d-flex align-items-center justify-content-center">
  <svg xmlns="http://www.w3.org/2000/svg"
       width="16"
       height="16"
       fill="currentColor"
       class="bi bi-plus-circle"
       viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
  </svg>
  &nbsp; New Client
</a>

findacoach/coach/templates/partials/button_start_session.html
<a href="{% url 'coach:coachingsession_create' client_id=client_id %}"
   class="btn btn-outline-primary d-flex align-items-center justify-content-center">
  <svg xmlns="http://www.w3.org/2000/svg"
       width="16"
       height="16"
       fill="currentColor"
       class="bi bi-calendar-plus"
       viewBox="0 0 16 16">
    <path d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7" />
    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z" />
  </svg>
  &nbsp; Start Session
</a>

findacoach/coach/templates/partials/button_view_client.html
<a href="{% url 'coach:client_detail' pk=1 %}"
   class="btn btn-outline-primary d-flex align-items-center justify-content-center">
  <svg xmlns="http://www.w3.org/2000/svg"
       width="16"
       height="16"
       fill="currentColor"
       class="bi bi-person"
       viewBox="0 0 16 16">
    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z" />
  </svg>
  &nbsp; Details
</a>